### ISSUE TITLE
Template request

### ISSUE THREAD

**Issue by Garda88** [nash-io/locale#35]
Hello, 

I am a member of Nash community but I made my account back when you didn't had to stake and now I can login to community but cannot post messages. Anyway, I want to contribute translating the UI of the exchange to Croatian/Bosnian/Serbian since these nations share a common language (the differences are like between American/Australian/UK in terms of English). Croatian is my native language. I've seen that Fabio made a video tutorial on how to work on Github but there is no file for Croatian/Bosnian/Serbian. Can you please send me a template so I can start working on it? I can translate the whole thing by myself I would just consult somebody to make sure all the terminology is adequate (Chris offered his help in the community topic). I don't know how to use Github (I registered today) and (for the moment) can't post on Nash community, so **can someone please email me at de9minimal@gmail.com so I can start working on this**.

Thanks

**Comment by canesin** [comment]
I added the base file https://github.com/nash-io/locale/blob/master/locales/hr_HR.json
